[package]
name = "escrow-program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.18.17"
borsh = "0.9.3"
borsh-derive = "0.9.1"
spl-token = { version="4.0.0", features = [ "no-entrypoint" ] }

pyth-sdk-solana = "0.2" 

[lib]
crate-type = ["cdylib", "lib"]